.gitignore, src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/telemetry/krkn_telemetry.py, src/krkn_lib/tests/test_utils.py, src/krkn_lib/utils/functions.py
This function will enable loading values from scenario yaml or setting default values.
=> Add function `get_scenario_items`

src/krkn_lib/models/telemetry/models.py, src/krkn_lib/telemetry/krkn_telemetry.py, src/krkn_lib/tests/test_krkn_telemetry.py
[krkn PR](https://github.com/redhat-chaos/krkn/pull/479)
=> Changes needed to support the print json functionality

.github/workflows/build.yaml
Run krkn build when krkn-lib tag updates
=> Build krkn

src/krkn_lib/k8s/krkn_kubernetes.py
This refactoring is aimed to add the compatibility with kubernetes of the prometheus backup feature to expand the kraken functional test suite and add the prometheus backup functionality also in Kubernetes. The main problem with the previous approach is that OCP prometheus container image provides a full featured bash shell with all the standard GNU tools (tar, split, bash syntax etc) while the K8S distribution (eg. the Helm one utilized in the GitHub action) are based on Busybox that ships minimal versions of the same tools. I reproduced the same functionalities using a minimal set of tools options that will run on both platforms keeping the functionality as much as possible similar to the previous version. 
The only breaking change is related to the archive files format uploaded on AWS: …
=> Prometheus refactoring to add K8S compatibility

pyproject.toml, src/krkn_lib/tests/test_krkn_telemetry_kubernetes.py, src/krkn_lib/tests/test_krkn_telemetry_openshift.py
Enables krkn to group telemetry runs by folders
=> Telemetry folders

src/krkn_lib/models/krkn/__init__.py, src/krkn_lib/models/krkn/models.py, src/krkn_lib/models/telemetry/models.py, src/krkn_lib/prometheus/krkn_prometheus.py, src/krkn_lib/telemetry/elastic.py, src/krkn_lib/telemetry/k8s/krkn_telemetry_kubernetes.py, src/krkn_lib/tests/test_krkn_elastic.py, src/krkn_lib/tests/test_krkn_kubernetes.py, src/krkn_lib/tests/test_krkn_prometheus.py, src/krkn_lib/tests/test_krkn_telemetry_kubernetes.py
*NOTE*: the changes made in the Elastic code are all automatically made by flake8 while linting the code, they can be ignored.
=> Adds support to add alerts as telemetry metadata

src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/tests/base_test.py, src/krkn_lib/tests/test_krkn_kubernetes.py, src/krkn_lib/tests/test_krkn_telemetry_kubernetes.py, src/testdata/net-policy.j2
On prow we are not able to create a network policy file on the system, going to be using the functions here in krkn to be able to not have to write out a file
=> Adding network policy create and delete

src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/models/telemetry/models.py, src/krkn_lib/ocp/krkn_openshift.py, src/krkn_lib/telemetry/k8s/krkn_telemetry_kubernetes.py, src/krkn_lib/telemetry/ocp/krkn_telemetry_openshift.py, src/krkn_lib/tests/test_krkn_kubernetes.py
Working on adding ocp version, need to test in krkn that get proper telemetry
=> Adding version to telemetry

src/krkn_lib/models/telemetry/models.py, src/krkn_lib/telemetry/k8s/krkn_telemetry_kubernetes.py, src/krkn_lib/telemetry/ocp/krkn_telemetry_openshift.py
Was not able to get version from elastic search, changing to cluster_version
=> Changing version to cluster version

src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/models/telemetry/models.py, src/krkn_lib/tests/test_krkn_telemetry_models.py, src/krkn_lib/tests/test_utils.py, src/krkn_lib/utils/functions.py
Using corev1 api to get cluster events 
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_event_for_all_namespaces
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_event
Returns [CoreV1EventList](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1EventList.md)  type
=> Cluster events

src/krkn_lib/elastic/krkn_elastic.py, src/krkn_lib/models/elastic/models.py, src/krkn_lib/telemetry/ocp/krkn_telemetry_openshift.py, src/krkn_lib/tests/test_krkn_elastic.py, src/krkn_lib/tests/test_version.py
Ran the following and it updated these files 
```
isort --profile black .
black --line-length 79 .
flake8 .
```
=> Formatting changes for running workflow commands locally

src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/k8s/templates/hog_pod.j2, src/krkn_lib/models/krkn/models.py, src/krkn_lib/tests/test_krkn_kubernetes_models.py
Add support for creating tolerations from taints
Related to krkn-chaos/krkn#790
=> Fix: Add support for taints

src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/tests/test_krkn_kubernetes_get.py
=> get_node_ip function in KrknKubernetes to remove kubectl dependency

.github/workflows/build.yaml
=> fixes the prometheus settings that makes the pipeline fail

.github/workflows/build.yaml
=> fixes the previous pypi fix

.github/workflows/build.yaml
Using global envionrment, hard code elastic search variables instead of repo variables 
=> Es env vars

src/krkn_lib/models/elastic/models.py, src/krkn_lib/tests/base_test.py, src/krkn_lib/tests/test_krkn_elastic_models.py
Adding node type into elastic node summary
=> Node summary

.github/release-template.md, .github/workflows/release.yml
=> [CNCF Incubation] Automatic release generation + SBOM

.github/workflows/release.yml
=> fixed release generation url

src/krkn_lib/k8s/krkn_kubernetes.py, src/krkn_lib/models/elastic/models.py, src/krkn_lib/models/telemetry/models.py, src/krkn_lib/tests/base_test.py, src/krkn_lib/tests/test_krkn_elastic_models.py, src/krkn_lib/tests/test_utils.py
=> fixes get_pid compatibility

.github/workflows/build.yaml
Adding new way to get ES password
=> Adding new es passowrd setup
